registry: docker.io/datadog
providers: #aks specific configuration to prevent an error when reconciling the webhook
  aks:
    enabled: true
datadog:
  env:
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  kubelet: #aks specific configuration due to how AKS has setup the SSL
    tlsVerify: false
  apm: # datadog.apm.portEnabled -- Enable APM over TCP communication (port 8126 by default)
    portEnabled: true
  logLevel: INFO #logging verbosity, valid log levels are: trace, debug, info, warn, error, critical, off
  logs:
     enabled: true
     containerCollectAll: true #allow log collection for all containers
  collectEvents: true
  networkMonitoring: #Enable NPM collection
    enabled: true
  logs: #Enable log collection
    enabled: true
    containerCollectAll: true
  processAgent: #real-time visibility into the process running on. Set to true to use orchestratorExplorer
    enabled: true
  orchestratorExplorer: #monitor the state of pods, deployments, and other Kubernetes concepts in a specific namespace or availability zone, view resource specifications for failed pods within a deployment, correlate node activity with related logs
    enabled: true
  kubeStateMetricsEnabled:
    enabled: true
  resources:
   requests:
     cpu: 20m
     memory: 25Mi
   limits:
     cpu: 200m
     memory: 256Mi
clusterAgent: #collecting cluster level monitoring data - datadog.collectEvents to true
  enabled: true
  replicas: 2
  createPodDisruptionBudget: true
  image:
    name: cluster-agent
    tag: latest
  containers:
    clusterAgent:
      securityContext:
        allowPrivilegeEscalation: false
  metricsProvider:
    enabled: true #Enable the metricsProvider to be able to scale based on metrics in Datadog
  rbac: 
    create: true
  resources:
   requests:
     cpu: 20m
     memory: 25Mi
   limits:
     cpu: 200m
     memory: 256Mi