apiVersion: v1
kind: Pod
metadata:
  name: java-service
  labels:
    admission.datadoghq.com/enabled: "true" #Enable Admission Controller to mutate new pods in this deployment
    tags.datadoghq.com/env: uat
    tags.datadoghq.com/service: java-service
    tags.datadoghq.com/version: "1.0.0"
  annotations:
    admission.datadoghq.com/java-lib.version: "latest" #Enable library injection for a specified tracing library.
    ad.datadoghq.com/java-service.logs: '[{"source": "java","service": "java-service","tags": ["env:uat"]}]'
spec:
  containers:
  - name: java-service
    image: nilushancosta/datadog-java-apm-demo
    ports:
    - containerPort: 8080
